name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches:
      - tolar_master
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tolar/blockscout
      PROJECT_ID: tolar-devops-311210
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: 'google-github-actions/setup-gcloud@v1'
      with:
        service_account_key: ${{ secrets.SER_GCP_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: cd ./docker && make build

    - name: GCP Auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{  secrets.SER_GCP_ACCOUNT_KEY }}
        
    - name: Push Docker Image to Container Registry (GCR)
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
