---
name: Build and Push Image to Google Cloud Platform
on:
  push:
    branches: [ tolar_master ]
    
env:
  IMAGE_NAME: tolar-blockscout
  GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
      
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: Tolar-HashNET/blockscout
          ref: tolar_master
        
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.SER_GCP_ACCOUNT_KEY }}
          registry: gcr.io
          project_id: ${{ env.GCR_PROJECT_ID }}
          image_name: ${{ env.IMAGE_NAME }}
          image_tag: latest
          dockerfile: ./docker/Dockerfile
          context: .
          build_args: RELEASE_VERSION=5.2.0

